<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Currency;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            ['name' => 'United Arab Emirates Dirham', 'code' => 'AED', 'symbol' => 'د.إ', 'number' => '784'],
            ['name' => 'Afghan Afghani', 'code' => 'AFN', 'symbol' => '؋', 'number' => '971'],
            ['name' => 'Albanian Lek', 'code' => 'ALL', 'symbol' => 'L', 'number' => '8'],
            ['name' => 'Armenian Dram', 'code' => 'AMD', 'symbol' => '֏', 'number' => '51'],
            ['name' => 'Netherlands Antillean Guilder', 'code' => 'ANG', 'symbol' => 'ƒ', 'number' => '532'],
            ['name' => 'Angolan Kwanza', 'code' => 'AOA', 'symbol' => 'Kz', 'number' => '973'],
            ['name' => 'Argentine Peso', 'code' => 'ARS', 'symbol' => '$', 'number' => '32'],
            ['name' => 'Australian Dollar', 'code' => 'AUD', 'symbol' => '$', 'number' => '36'],
            ['name' => 'Aruban Florin', 'code' => 'AWG', 'symbol' => 'ƒ', 'number' => '533'],
            ['name' => 'Azerbaijani Manat', 'code' => 'AZN', 'symbol' => '₼', 'number' => '944'],
            ['name' => 'Bosnia-Herzegovina Convertible Mark', 'code' => 'BAM', 'symbol' => 'КМ', 'number' => '977'],
            ['name' => 'Barbadian Dollar', 'code' => 'BBD', 'symbol' => '$', 'number' => '52'],
            ['name' => 'Bangladeshi Taka', 'code' => 'BDT', 'symbol' => '৳', 'number' => '50'],
            ['name' => 'Bulgarian Lev', 'code' => 'BGN', 'symbol' => 'лв', 'number' => '975'],
            ['name' => 'Bahraini Dinar', 'code' => 'BHD', 'symbol' => '.د.ب', 'number' => '48'],
            ['name' => 'Burundian Franc', 'code' => 'BIF', 'symbol' => 'FBu', 'number' => '108'],
            ['name' => 'Bermudian Dollar', 'code' => 'BMD', 'symbol' => '$', 'number' => '60'],
            ['name' => 'Brunei Dollar', 'code' => 'BND', 'symbol' => '$', 'number' => '96'],
            ['name' => 'Bolivian Boliviano', 'code' => 'BOB', 'symbol' => 'Bs.', 'number' => '68'],
            ['name' => 'Brazilian Real', 'code' => 'BRL', 'symbol' => 'R$', 'number' => '986'],
            ['name' => 'Bahamian Dollar', 'code' => 'BSD', 'symbol' => '$', 'number' => '44'],
            ['name' => 'Bhutanese Ngultrum', 'code' => 'BTN', 'symbol' => 'Nu.', 'number' => '64'],
            ['name' => 'Botswana Pula', 'code' => 'BWP', 'symbol' => 'P', 'number' => '72'],
            ['name' => 'Belarusian Ruble', 'code' => 'BYN', 'symbol' => 'Br', 'number' => '933'],
            ['name' => 'Belize Dollar', 'code' => 'BZD', 'symbol' => 'BZ$', 'number' => '84'],
            ['name' => 'Canadian Dollar', 'code' => 'CAD', 'symbol' => '$', 'number' => '124'],
            ['name' => 'Congolese Franc', 'code' => 'CDF', 'symbol' => 'FC', 'number' => '976'],
            ['name' => 'Swiss Franc', 'code' => 'CHF', 'symbol' => 'CHF', 'number' => '756'],
            ['name' => 'Chilean Peso', 'code' => 'CLP', 'symbol' => '$', 'number' => '152'],
            ['name' => 'Chinese Yuan Renminbi', 'code' => 'CNY', 'symbol' => '¥', 'number' => '156'],
            ['name' => 'Colombian Peso', 'code' => 'COP', 'symbol' => '$', 'number' => '170'],
            ['name' => 'Costa Rican Colón', 'code' => 'CRC', 'symbol' => '₡', 'number' => '188'],
            ['name' => 'Cuban Peso', 'code' => 'CUP', 'symbol' => '$', 'number' => '192'],
            ['name' => 'Cape Verdean Escudo', 'code' => 'CVE', 'symbol' => 'Esc', 'number' => '132'],
            ['name' => 'Czech Koruna', 'code' => 'CZK', 'symbol' => 'Kč', 'number' => '203'],
            ['name' => 'Djiboutian Franc', 'code' => 'DJF', 'symbol' => 'Fdj', 'number' => '262'],
            ['name' => 'Danish Krone', 'code' => 'DKK', 'symbol' => 'kr', 'number' => '208'],
            ['name' => 'Dominican Peso', 'code' => 'DOP', 'symbol' => 'RD$', 'number' => '214'],
            ['name' => 'Algerian Dinar', 'code' => 'DZD', 'symbol' => 'د.ج', 'number' => '12'],
            ['name' => 'Egyptian Pound', 'code' => 'EGP', 'symbol' => 'ج.م', 'number' => '818'],
            ['name' => 'Eritrean Nakfa', 'code' => 'ERN', 'symbol' => 'Nfk', 'number' => '232'],
            ['name' => 'Ethiopian Birr', 'code' => 'ETB', 'symbol' => 'Br', 'number' => '230'],
            ['name' => 'Euro', 'code' => 'EUR', 'symbol' => '€', 'number' => '978'],
            ['name' => 'Fijian Dollar', 'code' => 'FJD', 'symbol' => 'FJ$', 'number' => '242'],
            ['name' => 'Falkland Islands Pound', 'code' => 'FKP', 'symbol' => '£', 'number' => '238'],
            ['name' => 'Faroese Króna', 'code' => 'FOK', 'symbol' => 'kr', 'number' => '234'],
            ['name' => 'British Pound Sterling', 'code' => 'GBP', 'symbol' => '£', 'number' => '826'],
            ['name' => 'Georgian Lari', 'code' => 'GEL', 'symbol' => '₾', 'number' => '981'],
            ['name' => 'Guernsey Pound', 'code' => 'GGP', 'symbol' => '£', 'number' => '831'],
            ['name' => 'Ghanaian Cedi', 'code' => 'GHS', 'symbol' => 'GH₵', 'number' => '936'],
            ['name' => 'Gibraltar Pound', 'code' => 'GIP', 'symbol' => '£', 'number' => '292'],
            ['name' => 'Gambian Dalasi', 'code' => 'GMD', 'symbol' => 'D', 'number' => '270'],
            ['name' => 'Guinean Franc', 'code' => 'GNF', 'symbol' => 'FG', 'number' => '324'],
            ['name' => 'Guatemalan Quetzal', 'code' => 'GTQ', 'symbol' => 'Q', 'number' => '320'],
            ['name' => 'Guyanaese Dollar', 'code' => 'GYD', 'symbol' => 'G$', 'number' => '328'],
            ['name' => 'Hong Kong Dollar', 'code' => 'HKD', 'symbol' => '$', 'number' => '344'],
            ['name' => 'Honduran Lempira', 'code' => 'HNL', 'symbol' => 'L', 'number' => '340'],
            ['name' => 'Haitian Gourde', 'code' => 'HTG', 'symbol' => 'G', 'number' => '332'],
            ['name' => 'Hungarian Forint', 'code' => 'HUF', 'symbol' => 'Ft', 'number' => '348'],
            ['name' => 'Indonesian Rupiah', 'code' => 'IDR', 'symbol' => 'Rp', 'number' => '360'],
            ['name' => 'Israeli New Shekel', 'code' => 'ILS', 'symbol' => '₪', 'number' => '376'],
            ['name' => 'Manx pound', 'code' => 'IMP', 'symbol' => '£', 'number' => '833'],
            ['name' => 'Indian Rupee', 'code' => 'INR', 'symbol' => '₹', 'number' => '356'],
            ['name' => 'Iraqi Dinar', 'code' => 'IQD', 'symbol' => 'ع.د', 'number' => '368'],
            ['name' => 'Iranian Rial', 'code' => 'IRR', 'symbol' => '﷼', 'number' => '364'],
            ['name' => 'Icelandic Króna', 'code' => 'ISK', 'symbol' => 'kr', 'number' => '352'],
            ['name' => 'Jersey Pound', 'code' => 'JEP', 'symbol' => '£', 'number' => '832'],
            ['name' => 'Jamaican Dollar', 'code' => 'JMD', 'symbol' => 'J$', 'number' => '388'],
            ['name' => 'Jordanian Dinar', 'code' => 'JOD', 'symbol' => 'د.ا', 'number' => '400'],
            ['name' => 'Japanese Yen', 'code' => 'JPY', 'symbol' => '¥', 'number' => '392'],
            ['name' => 'Kenyan Shilling', 'code' => 'KES', 'symbol' => 'KSh', 'number' => '404'],
            ['name' => 'Kyrgyzstani Som', 'code' => 'KGS', 'symbol' => 'с', 'number' => '417'],
            ['name' => 'Cambodian Riel', 'code' => 'KHR', 'symbol' => '៛', 'number' => '116'],
            ['name' => 'Kiribati Dollar', 'code' => 'KID', 'symbol' => '$', 'number' => '296'],
            ['name' => 'Comorian Franc', 'code' => 'KMF', 'symbol' => 'CF', 'number' => '174'],
            ['name' => 'North Korean Won', 'code' => 'KPW', 'symbol' => '₩', 'number' => '408'],
            ['name' => 'South Korean Won', 'code' => 'KRW', 'symbol' => '₩', 'number' => '410'],
            ['name' => 'Kuwaiti Dinar', 'code' => 'KWD', 'symbol' => 'د.ك', 'number' => '414'],
            ['name' => 'Cayman Islands Dollar', 'code' => 'KYD', 'symbol' => '$', 'number' => '136'],
            ['name' => 'Kazakhstani Tenge', 'code' => 'KZT', 'symbol' => '〒', 'number' => '398'],
            ['name' => 'Lao Kip', 'code' => 'LAK', 'symbol' => '₭', 'number' => '418'],
            ['name' => 'Lebanese Pound', 'code' => 'LBP', 'symbol' => 'ل.ل', 'number' => '422'],
            ['name' => 'Sri Lankan Rupee', 'code' => 'LKR', 'symbol' => 'Rs', 'number' => '144'],
            ['name' => 'Liberian Dollar', 'code' => 'LRD', 'symbol' => '$', 'number' => '430'],
            ['name' => 'Lesotho Loti', 'code' => 'LSL', 'symbol' => 'L', 'number' => '426'],
            ['name' => 'Libyan Dinar', 'code' => 'LYD', 'symbol' => 'ل.د', 'number' => '434'],
            ['name' => 'Moroccan Dirham', 'code' => 'MAD', 'symbol' => 'د.م.', 'number' => '504'],
            ['name' => 'Moldovan Leu', 'code' => 'MDL', 'symbol' => 'L', 'number' => '498'],
            ['name' => 'Malagasy Ariary', 'code' => 'MGA', 'symbol' => 'Ar', 'number' => '969'],
            ['name' => 'Macedonian Denar', 'code' => 'MKD', 'symbol' => 'ден', 'number' => '807'],
            ['name' => 'Myanmar Kyat', 'code' => 'MMK', 'symbol' => 'K', 'number' => '104'],
            ['name' => 'Mongolian Tugrik', 'code' => 'MNT', 'symbol' => '₮', 'number' => '496'],
            ['name' => 'Macanese Pataca', 'code' => 'MOP', 'symbol' => 'MOP$', 'number' => '446'],
            ['name' => 'Mauritanian Ouguiya', 'code' => 'MRU', 'symbol' => 'UM', 'number' => '929'],
            ['name' => 'Mauritian Rupee', 'code' => 'MUR', 'symbol' => '₨', 'number' => '480'],
            ['name' => 'Maldivian Rufiyaa', 'code' => 'MVR', 'symbol' => 'ރ.', 'number' => '462'],
            ['name' => 'Malawian Kwacha', 'code' => 'MWK', 'symbol' => 'MK', 'number' => '454'],
            ['name' => 'Mexican Peso', 'code' => 'MXN', 'symbol' => '$', 'number' => '484'],
            ['name' => 'Malaysian Ringgit', 'code' => 'MYR', 'symbol' => 'RM', 'number' => '458'],
            ['name' => 'Mozambican Metical', 'code' => 'MZN', 'symbol' => 'MT', 'number' => '943'],
            ['name' => 'Namibian Dollar', 'code' => 'NAD', 'symbol' => '$', 'number' => '516'],
            ['name' => 'Nigerian Naira', 'code' => 'NGN', 'symbol' => '₦', 'number' => '566'],
            ['name' => 'Nicaraguan Córdoba', 'code' => 'NIO', 'symbol' => 'C$', 'number' => '558'],
            ['name' => 'Norwegian Krone', 'code' => 'NOK', 'symbol' => 'kr', 'number' => '578'],
            ['name' => 'Nepalese Rupee', 'code' => 'NPR', 'symbol' => 'रू', 'number' => '524'],
            ['name' => 'New Zealand Dollar', 'code' => 'NZD', 'symbol' => '$', 'number' => '554'],
            ['name' => 'Omani Rial', 'code' => 'OMR', 'symbol' => 'ر.ع.', 'number' => '512'],
            ['name' => 'Panamanian Balboa', 'code' => 'PAB', 'symbol' => 'B/.', 'number' => '590'],
            ['name' => 'Peruvian Nuevo Sol', 'code' => 'PEN', 'symbol' => 'S/', 'number' => '604'],
            ['name' => 'Papua New Guinean Kina', 'code' => 'PGK', 'symbol' => 'K', 'number' => '598'],
            ['name' => 'Philippine Peso', 'code' => 'PHP', 'symbol' => '₱', 'number' => '608'],
            ['name' => 'Pakistani Rupee', 'code' => 'PKR', 'symbol' => '₨', 'number' => '586'],
            ['name' => 'Polish Zloty', 'code' => 'PLN', 'symbol' => 'zł', 'number' => '985'],
            ['name' => 'Paraguayan Guarani', 'code' => 'PYG', 'symbol' => '₲', 'number' => '600'],
            ['name' => 'Qatari Riyal', 'code' => 'QAR', 'symbol' => 'ر.ق', 'number' => '634'],
            ['name' => 'Romanian Leu', 'code' => 'RON', 'symbol' => 'lei', 'number' => '946'],
            ['name' => 'Serbian Dinar', 'code' => 'RSD', 'symbol' => 'дин.', 'number' => '941'],
            ['name' => 'Russian Ruble', 'code' => 'RUB', 'symbol' => '₽', 'number' => '643'],
            ['name' => 'Rwandan Franc', 'code' => 'RWF', 'symbol' => 'FRw', 'number' => '646'],
            ['name' => 'Saudi Riyal', 'code' => 'SAR', 'symbol' => 'ر.س', 'number' => '682'],
            ['name' => 'Solomon Islands Dollar', 'code' => 'SBD', 'symbol' => 'SI$', 'number' => '90'],
            ['name' => 'Seychellois Rupee', 'code' => 'SCR', 'symbol' => '₨', 'number' => '690'],
            ['name' => 'Sudanese Pound', 'code' => 'SDG', 'symbol' => 'SDG', 'number' => '938'],
            ['name' => 'Swedish Krona', 'code' => 'SEK', 'symbol' => 'kr', 'number' => '752'],
            ['name' => 'Singapore Dollar', 'code' => 'SGD', 'symbol' => '$', 'number' => '702'],
            ['name' => 'Saint Helena Pound', 'code' => 'SHP', 'symbol' => '£', 'number' => '654'],
            ['name' => 'Sierra Leonean Leone', 'code' => 'SLL', 'symbol' => 'Le', 'number' => '694'],
            ['name' => 'Somali Shilling', 'code' => 'SOS', 'symbol' => 'Sh', 'number' => '706'],
            ['name' => 'Surinamese Dollar', 'code' => 'SRD', 'symbol' => '$', 'number' => '968'],
            ['name' => 'South Sudanese Pound', 'code' => 'SSP', 'symbol' => 'SSP', 'number' => '728'],
            ['name' => 'São Tomé and Príncipe Dobra', 'code' => 'STN', 'symbol' => 'Db', 'number' => '930'],
            ['name' => 'Syrian Pound', 'code' => 'SYP', 'symbol' => '£S', 'number' => '760'],
            ['name' => 'Swazi Lilangeni', 'code' => 'SZL', 'symbol' => 'E', 'number' => '748'],
            ['name' => 'Thai Baht', 'code' => 'THB', 'symbol' => '฿', 'number' => '764'],
            ['name' => 'Tajikistani Somoni', 'code' => 'TJS', 'symbol' => 'ЅМ', 'number' => '972'],
            ['name' => 'Turkmenistani Manat', 'code' => 'TMT', 'symbol' => 'm', 'number' => '934'],
            ['name' => 'Tunisian Dinar', 'code' => 'TND', 'symbol' => 'د.ت', 'number' => '788'],
            ['name' => 'Tongan Paʻanga', 'code' => 'TOP', 'symbol' => 'T$', 'number' => '776'],
            ['name' => 'Turkish Lira', 'code' => 'TRY', 'symbol' => '₺', 'number' => '949'],
            ['name' => 'Trinidad and Tobago Dollar', 'code' => 'TTD', 'symbol' => 'TT$', 'number' => '780'],
            ['name' => 'New Taiwan Dollar', 'code' => 'TWD', 'symbol' => 'NT$', 'number' => '901'],
            ['name' => 'Tanzanian Shilling', 'code' => 'TZS', 'symbol' => 'TSh', 'number' => '834'],
            ['name' => 'Ukrainian Hryvnia', 'code' => 'UAH', 'symbol' => '₴', 'number' => '980'],
            ['name' => 'Ugandan Shilling', 'code' => 'UGX', 'symbol' => 'USh', 'number' => '800'],
            ['name' => 'United States Dollar', 'code' => 'USD', 'symbol' => '$', 'number' => '840'],
            ['name' => 'Uruguayan Peso', 'code' => 'UYU', 'symbol' => '$U', 'number' => '858'],
            ['name' => 'Uzbekistan Som', 'code' => 'UZS', 'symbol' => 'UZS', 'number' => '860'],
            ['name' => 'Venezuelan Bolívar Soberano', 'code' => 'VES', 'symbol' => 'Bs.S.', 'number' => '928'],
            ['name' => 'Vietnamese Dong', 'code' => 'VND', 'symbol' => '₫', 'number' => '704'],
            ['name' => 'Vanuatu Vatu', 'code' => 'VUV', 'symbol' => 'VT', 'number' => '548'],
            ['name' => 'Samoan Tala', 'code' => 'WST', 'symbol' => 'WS$', 'number' => '882'],
            ['name' => 'East Caribbean Dollar', 'code' => 'XCD', 'symbol' => '$', 'number' => '951'],
            ['name' => 'CFP Franc', 'code' => 'XPF', 'symbol' => '₣', 'number' => '953'],
            ['name' => 'Yemeni Rial', 'code' => 'YER', 'symbol' => '﷼', 'number' => '886'],
            ['name' => 'South African Rand', 'code' => 'ZAR', 'symbol' => 'R', 'number' => '710'],
            ['name' => 'Zambian Kwacha', 'code' => 'ZMW', 'symbol' => 'ZK', 'number' => '967'],
            ['name' => 'Zimbabwean Dollar', 'code' => 'ZWL', 'symbol' => 'Z$', 'number' => '932'],

            ['name' => 'Bitcoin', 'code' => 'BTC', 'symbol' => '₿', 'number' => '0'],
            ['name' => 'Ethereum', 'code' => 'ETH', 'symbol' => 'Ξ', 'number' => '0'],
            ['name' => 'Tether', 'code' => 'USDT', 'symbol' => '₮', 'number' => '0'],
            ['name' => 'Cardano', 'code' => 'ADA', 'symbol' => '₳', 'number' => '0'],
            ['name' => 'XRP', 'code' => 'XRP', 'symbol' => '✕', 'number' => '0'],
            ['name' => 'Solana', 'code' => 'SOL', 'symbol' => '◎', 'number' => '0'],
            ['name' => 'Polkadot', 'code' => 'DOT', 'symbol' => '●', 'number' => '0'],
            ['name' => 'Dogecoin', 'code' => 'DOGE', 'symbol' => 'Ð', 'number' => '0'],
            ['name' => 'Dai', 'code' => 'DAI', 'symbol' => '◈', 'number' => '0'],
            ['name' => 'Litecoin', 'code' => 'LTC', 'symbol' => 'Ł', 'number' => '0'],
            ['name' => 'Algorand', 'code' => 'ALGO', 'symbol' => 'Ⱥ', 'number' => '0'],
            ['name' => 'Bitcoin Cash', 'code' => 'BCH', 'symbol' => 'Ƀ', 'number' => '0'],
            ['name' => 'ECOMI', 'code' => 'OMI', 'symbol' => 'Ο', 'number' => '0'],
            ['name' => 'Internet Computer', 'code' => 'ICP', 'symbol' => '∞', 'number' => '0'],
            ['name' => 'Ethereum Classic', 'code' => 'ETC', 'symbol' => 'ξ', 'number' => '0'],
            ['name' => 'Monero', 'code' => 'XMR', 'symbol' => 'ɱ', 'number' => '0'],
            ['name' => 'Tezos', 'code' => 'XTZ', 'symbol' => 'ꜩ', 'number' => '0'],
            ['name' => 'Iota', 'code' => 'MIOTA', 'symbol' => 'ɨ', 'number' => '0'],
            ['name' => 'EOS', 'code' => 'EOS', 'symbol' => 'ε', 'number' => '0'],
            ['name' => 'Bitcoin SV', 'code' => 'BSV', 'symbol' => 'Ɓ', 'number' => '0'],
            ['name' => 'Maker', 'code' => 'MKR', 'symbol' => 'Μ', 'number' => '0'],
            ['name' => 'Zcash', 'code' => 'ZEC', 'symbol' => 'ⓩ', 'number' => '0'],
            ['name' => 'Dash', 'code' => 'DASH', 'symbol' => 'Đ', 'number' => '0'],
            ['name' => 'Nano', 'code' => 'XNO', 'symbol' => 'Ӿ', 'number' => '0'],
            ['name' => 'Augur', 'code' => 'REP', 'symbol' => 'Ɍ', 'number' => '0'],
            ['name' => 'Steem', 'code' => 'STEEM', 'symbol' => 'ȿ', 'number' => '0'],
        ];

        foreach ($currencies as $currency) {
            Currency::create($currency);
        }
    }
}
